name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # we build monthly at 00:00 on day-of-month 1
    #- cron:  '0 0 1 * *'
    # we build weekly at 00:01 on Sunday.
    - cron:  '1 0 * * 0'

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
      - uses: actions/checkout@v6

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install

      - name: Lint check
        run: poetry run flake8 bot

#      - name: Type Hints check
#        run: poetry run mypy .
