name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # we build monthly at 00:00 on day-of-month 1
    #- cron:  '0 0 1 * *'
    # we build weekly at 00:00 on Sunday.
    - cron:  '0 0 * * 0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      # https://github.com/marketplace/actions/docker-login
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      # https://github.com/marketplace/actions/build-and-push-docker-images
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: xbgmsharp/postgsail-telegram-bot:latest
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag xbgmsharp/postgsail-telegram-bot
##      run: docker build . --file Dockerfile --tag xbgmsharp/postgsail-telegram-bot:$(date +%s)
